### ISSUE TITLE
Crash on joining in world/server

### ISSUE THREAD

**Issue by lynrayy** [EngineHub/WorldEditCUI#50]
The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: 'void com.mojang.blaze3d.systems.RenderSystem.glMultiTexCoord2f(int, float, float)'
**Fabric, 1.17.1**

**Comment by jminer-kraft** [comment]
I have the same problem. It gave error code 255 if that helps anyone figure out what is wrong.

**Comment by OLEGSHA** [comment]
There's a developer build available [here](https://github.com/EngineHub/WorldEditCUI/suites/3702643006/artifacts/90370588). Use that.

**Comment by lynrayy** [comment]
Uhh...
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'worldeditcui'!
-1

**Comment by zml2008** [comment]
Experimental development builds are available at your own risk. Do not use them unless you are able to handle brokenness on your own.

**Comment by OLEGSHA** [comment]
Use the file named `WorldEditCUI-1.17.1+01-SNAPSHOT.jar`, without `-dev`. The `-dev` file is for mod development.

@zml2008, sure. I'm just helping people with the issue, since Fabric mods are sometime compatible between versions, and many people assume the 1.16.5 version will work on 1.17, especially since there's no highly-visible announcement on the topic.

**Comment by lynrayy** [comment]
Lol he closed issue 

Ok. It’s on your conscience, a mischief.
The second build (withoud -dev), by the way, started, but does not display anything

**Comment by lynrayy** [comment]
OLEGSHA thank you anyway
